import { ReelListing, SAAOInfo, Comment } from './types';

export const REEL_LISTINGS: ReelListing[] = [
  {
    id: 'reel_1',
    titleEn: 'Fresh Spinach (Palong Shak)',
    titleBn: 'তাজা পালং শাক (শৈবাল মুক্ত)',
    sellerEn: 'M. S. Al-Amin',
    sellerBn: 'আলামিন ট্রেডার্স',
    sellerRating: 4.9,
    sellerJobs: 134,
    locationEn: 'Shibganj, Bogura',
    locationBn: 'শিবগঞ্জ, বগুড়া',
    distanceKm: 184,
    stockEn: '2.4 Tons Available',
    stockBn: '২.৪ টন মজুদ আছে',
    pricePerUnitEn: '45 BDT',
    pricePerUnitBn: '৪৫ টাকা',
    unitEn: 'KG',
    unitBn: 'কেজি',
    category: 'spinach',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Harvested today morning, premium cold-box distribution, must dispatch within 12 hours.',
    zoneDescBn: 'আজ সকালে তোলা, প্রিমিয়াম কোল্ড-বক্স ডেলিভারি, ১২ ঘণ্টার মধ্যে সরবরাহ সম্পন্ন হবে।',
    bgGradient: 'from-emerald-950/80 to-stone-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=600&auto=format&fit=crop',
    likes: 245,
    comments: [
      {
        id: 'c1',
        userEn: 'Arif Hasan (Dhaka Corp)',
        userBn: 'আরিফ হাসান (ঢাকা কর্প)',
        textEn: 'Excellent freshness index! Just placed holding deposit.',
        textBn: 'চমৎকার তাজা ভাব! বুকিং সম্পন্ন করেছি।',
        timeEn: '10m ago',
        timeBn: '১০ মি আগে'
      },
      {
        id: 'c2',
        userEn: 'K. Islam',
        userBn: 'কে. ইসলাম',
        textEn: 'Is delivery to Kawran Bazar included?',
        textBn: 'কারওয়ান বাজার ডেলিভারি কি এর অন্তর্ভুক্ত?',
        timeEn: '32m ago',
        timeBn: '৩২ মি আগে'
      }
    ]
  },
  {
    id: 'reel_2',
    titleEn: 'Premium Gopalbhog Mangoes',
    titleBn: 'প্রিমিয়াম গোপালভোগ আম',
    sellerEn: 'Charghat Agro Cooperative',
    sellerBn: 'চারঘাট এগ্রো সমবায়',
    sellerRating: 4.8,
    sellerJobs: 412,
    locationEn: 'Charghat, Rajshahi',
    locationBn: 'চারঘাট, রাজশাহী',
    distanceKm: 240,
    stockEn: '12.0 Tons Available',
    stockBn: '১২.০ টন মজুদ আছে',
    pricePerUnitEn: '3,200 BDT',
    pricePerUnitBn: '৩,২০০ টাকা',
    unitEn: 'Maund (৪০ KG)',
    unitBn: 'মণ (৪০ কেজি)',
    category: 'mango',
    zoneEn: 'Buffer',
    zoneBn: 'বাফার',
    zoneDescEn: 'Preserved inside specialized DAE-approved ethylene buffer storehouses. Dispatches immediately.',
    zoneDescBn: 'ডিএই অনুমোদিত বিশেষায়িত বাফার স্টোরহাউজে সংরক্ষিত। অবিলম্বে ডেলিভারিযোগ্য।',
    bgGradient: 'from-amber-950/80 to-neutral-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=600&auto=format&fit=crop',
    likes: 812,
    comments: [
      {
        id: 'c3',
        userEn: 'Fahim Shahriar',
        userBn: 'ফাহিম শাহরিয়ার',
        textEn: 'The size look uniform, great packaging protocol.',
        textBn: 'আকার বেশ চমৎকার ও সুষম, প্যাকেজিং দারুণ।',
        timeEn: '1h ago',
        timeBn: '১ ঘণ্টা আগে'
      }
    ]
  },
  {
    id: 'reel_3',
    titleEn: 'Imported Premium Almonds',
    titleBn: 'আমদানিকৃত প্রিমিয়াম কাঠবাদাম',
    sellerEn: 'Chittagong Port Bonded Store',
    sellerBn: 'চট্টগ্রাম পোর্ট বন্ডেড গোডাউন',
    sellerRating: 4.95,
    sellerJobs: 89,
    locationEn: 'Karnaphuli Vault, CTG',
    locationBn: 'কর্ণফুলী ভল্ট, চট্টগ্রাম',
    distanceKm: 265,
    stockEn: '400 Bags (20 Tons)',
    stockBn: '৪০০ বস্তা (২০ টন)',
    pricePerUnitEn: '18,500 BDT',
    pricePerUnitBn: '১৮,৫০০ টাকা',
    unitEn: 'Bag (50 KG)',
    unitBn: 'বস্তা (৫০ কেজি)',
    category: 'almonds',
    zoneEn: 'Vault',
    zoneBn: 'ভল্ট',
    zoneDescEn: 'Secured inside temperature-controlled high-security custom vault. Standard collateral release.',
    zoneDescBn: 'তাপমাত্রা নিয়ন্ত্রিত ও উচ্চ নিরাপত্তাবেষ্টিত কাস্টম ভল্টে সংরক্ষিত। ব্যাংক কোল্যাটারাল ছাড়যোগ্য।',
    bgGradient: 'from-amber-900/80 to-zinc-950/40',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6cd9?q=80&w=600&auto=format&fit=crop',
    likes: 1391,
    comments: [
      {
        id: 'c4',
        userEn: 'Rahman Food Ltd.',
        userBn: 'রহমান ফুড লিঃ',
        textEn: 'Authentic quality, perfect moisture level for processing.',
        textBn: 'একদম খাঁটি মান, প্রসেস করার জন্য চমৎকার আর্দ্রতা মাত্রা।',
        timeEn: '4h ago',
        timeBn: '৪ ঘণ্টা আগে'
      }
    ]
  },
  {
    id: 'reel_shonali',
    titleEn: 'Gold-grade Shonali Chicken (Bulk)',
    titleBn: 'স্বর্ণ-মান সোনালী মুরগি (পাইকারি)',
    sellerEn: 'Narsingdi Poultry Farm',
    sellerBn: 'নরসিংদী পোল্ট্রি খামার',
    sellerRating: 4.8,
    sellerJobs: 215,
    locationEn: 'Sadar, Narsingdi',
    locationBn: 'সদর, নরসিংদী',
    distanceKm: 55,
    stockEn: '1,500 Pcs Available',
    stockBn: '১,৫০০ পিস উপলব্ধ',
    pricePerUnitEn: '240 BDT',
    pricePerUnitBn: '২৪০ টাকা',
    unitEn: 'Piece',
    unitBn: 'পিস',
    category: 'shonali',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Live Shonali bulk stock. Verified immunization logs. Transported in standard biological cage vans.',
    zoneDescBn: 'সক্রিয় সোনালী মুরগির পাইকারি লট। টিকাদান রেকর্ড যাচাইকৃত। নিয়মিত বায়োলজিক্যাল ভ্যানে পরিবহনযোগ্য।',
    bgGradient: 'from-amber-950/85 to-zinc-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?q=80&w=600&auto=format&fit=crop',
    likes: 310,
    comments: []
  },
  {
    id: 'reel_broiler',
    titleEn: 'High-Yield Broiler Chicken (Bulk)',
    titleBn: 'ব্রয়লার মুরগি (পাইকারি লটস)',
    sellerEn: 'Gazipur Feed & Livestock',
    sellerBn: 'গাজীপুর ফিড এন্ড লাইভস্টক',
    sellerRating: 4.7,
    sellerJobs: 330,
    locationEn: 'Sreepur, Gazipur',
    locationBn: 'শ্রীপুর, গাজীপুর',
    distanceKm: 42,
    stockEn: '4,000 KG Available',
    stockBn: '৪,০০০ কেজি উপলব্ধ',
    pricePerUnitEn: '165 BDT',
    pricePerUnitBn: '১৬৫ টাকা',
    unitEn: 'KG',
    unitBn: 'কেজি',
    category: 'broiler',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Healthy broiler chickens ready for bulk market lift. Direct farm pick-up available.',
    zoneDescBn: 'স্বাস্থ্যকর ব্রয়লার মুরগি পাইকারি বিক্রির জন্য তৈরি। খামার থেকে সরাসরি সংগ্রহের সুবিধা রয়েছে।',
    bgGradient: 'from-orange-950/80 to-stone-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?q=80&w=600&auto=format&fit=crop',
    likes: 450,
    comments: []
  },
  {
    id: 'reel_ducks',
    titleEn: 'Pekin & Deshi Cross Ducks',
    titleBn: 'পেকিন ও দেশি ক্রস হাঁস (পাইকারি)',
    sellerEn: 'Haor Fisheries & Ducks',
    sellerBn: 'হাওর ফিশারিজ ও হাঁস প্রজনন কেন্দ্র',
    sellerRating: 4.9,
    sellerJobs: 178,
    locationEn: 'Sunamganj Haor Basin',
    locationBn: 'সুনামগঞ্জ হাওর অঞ্চল',
    distanceKm: 270,
    stockEn: '800 Pcs Available',
    stockBn: '৮০০ পিস উপলব্ধ',
    pricePerUnitEn: '320 BDT',
    pricePerUnitBn: '৩২০ টাকা',
    unitEn: 'Piece',
    unitBn: 'পিস',
    category: 'ducks',
    zoneEn: 'Buffer',
    zoneBn: 'বাফার',
    zoneDescEn: 'Naturally fed open-water lake healthy ducks. Heavy bulk weight index approved.',
    zoneDescBn: 'প্রাকৃতিক হাওরে বড় হওয়া সুস্থ পুষ্টিকর হাঁস। গড় ওজন সূচক ডিএই অনুমোদিত।',
    bgGradient: 'from-sky-950/80 to-neutral-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1555890505-1aff66560ef7?q=80&w=600&auto=format&fit=crop',
    likes: 195,
    comments: []
  },
  {
    id: 'reel_beef',
    titleEn: 'Halal Grass-Fed Beef Meat',
    titleBn: 'তাজা গরুর মাংস (হালাল বাল্ক)',
    sellerEn: 'Bengal Agro Meat',
    sellerBn: 'বেঙ্গল এগ্রো মিট',
    sellerRating: 4.92,
    sellerJobs: 295,
    locationEn: 'Savar Cold Hub, Dhaka',
    locationBn: 'সাভার কোল্ড হাব, ঢাকা',
    distanceKm: 28,
    stockEn: '1,200 KG Available',
    stockBn: '১,২০০ কেজি উপলব্ধ',
    pricePerUnitEn: '720 BDT',
    pricePerUnitBn: '৭২০ টাকা',
    unitEn: 'KG',
    unitBn: 'কেজি',
    category: 'beef',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Strictly monitored disease-free certified beef. Temperature-locked cold chain delivery.',
    zoneDescBn: 'রোগ-জীবাণুমুক্ত প্রত্যয়িত হালাল গরুর মাংস। কোল্ড-চেইন নিয়ন্ত্রিত গাড়ি দ্বারা সরাসরি ডেলিভারি।',
    bgGradient: 'from-red-950/80 to-stone-900/40',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    likes: 580,
    comments: []
  },
  {
    id: 'reel_cows',
    titleEn: 'Prime Sahiwal Breed Milk/Meat Cows',
    titleBn: 'প্রিমিয়াম শাহীওয়াল জাতের গরু',
    sellerEn: 'Sirajganj Dairy Co',
    sellerBn: 'সিরাজগঞ্জ ডেইরি কো-অপারেটিভ',
    sellerRating: 4.88,
    sellerJobs: 334,
    locationEn: 'Shahjadpur, Sirajganj',
    locationBn: 'শাহজাদপুর, সিরাজগঞ্জ',
    distanceKm: 135,
    stockEn: '15 Heads Available',
    stockBn: '১৫ টি গরু মজুদ আছে',
    pricePerUnitEn: '145,000 BDT',
    pricePerUnitBn: '১,৪৫,০০০ টাকা',
    unitEn: 'Head',
    unitBn: 'টি',
    category: 'cows',
    zoneEn: 'Buffer',
    zoneBn: 'বাফার',
    zoneDescEn: 'Vaccinated high-yield Sahiwal breed live cows. DAE wellness clearance uploaded.',
    zoneDescBn: 'টিকাপ্রাপ্ত উচ্চ উৎপাদনশীল শাহীওয়াল জাতের জীবন্ত গরু। নিয়মিত প্রাণিসম্পদ ছাড়পত্রযুক্ত।',
    bgGradient: 'from-[#2e1d0c] to-[#121212]',
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=600&auto=format&fit=crop',
    likes: 924,
    comments: []
  },
  {
    id: 'reel_goats',
    titleEn: 'Pure Black Bengal Goats',
    titleBn: 'খাঁটি ব্ল্যাক বেঙ্গল ছাগল (লাইভ)',
    sellerEn: 'Chuadanga Livestock Farm',
    sellerBn: 'চুয়াডাঙ্গা ব্ল্যাক বেঙ্গল প্রজেক্ট',
    sellerRating: 4.94,
    sellerJobs: 167,
    locationEn: 'Chuadanga Sadar',
    locationBn: 'চুয়াডাঙ্গা সদর',
    distanceKm: 210,
    stockEn: '45 Heads Available',
    stockBn: '৪৫ টি ছাগল মজুদ আছে',
    pricePerUnitEn: '16,000 BDT',
    pricePerUnitBn: '১৬,০০০ টাকা',
    unitEn: 'Head',
    unitBn: 'টি',
    category: 'goats',
    zoneEn: 'Buffer',
    zoneBn: 'বাফার',
    zoneDescEn: 'Chuadanga authentic cross or pure Black Bengal goats. Premium quality organic weight.',
    zoneDescBn: 'চুয়াডাঙ্গার খাঁটি ও রোগমুক্ত সুস্থ ব্ল্যাক বেঙ্গল ছাগল। প্রিমিয়াম পুষ্টিকর মাংসের জন্য সেরা জাত।',
    bgGradient: 'from-zinc-900 to-stone-950',
    imageUrl: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?q=80&w=600&auto=format&fit=crop',
    likes: 382,
    comments: []
  },
  {
    id: 'reel_green_chilli',
    titleEn: 'Fresh Organic Green Chilli',
    titleBn: 'কাঁচা ও তাজা কাঁচা মরিচ (বাল্ক)',
    sellerEn: 'Bogra Agro Sourcing',
    sellerBn: 'বগুড়া এগ্রো সোর্সিং',
    sellerRating: 4.85,
    sellerJobs: 140,
    locationEn: 'Mahasthangarh, Bogra',
    locationBn: 'মহাস্থানগড়, বগুড়া',
    distanceKm: 190,
    stockEn: '1.8 Tons Available',
    stockBn: '১.৮ টন উপলব্ধ আছে',
    pricePerUnitEn: '90 BDT',
    pricePerUnitBn: '৯০ টাকা',
    unitEn: 'KG',
    unitBn: 'কেজি',
    category: 'green_chilli',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Intense green, heat-graded organic chillies. Sourced from native Bogra riverine delta fields.',
    zoneDescBn: 'তীব্র ঝাল ও তাজা প্রাকৃতিক কাঁচা মরিচ। বগুড়ার চর অঞ্চল থেকে সরাসরি সংগৃহীত।',
    bgGradient: 'from-emerald-900/90 to-neutral-900/30',
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119cb665?q=80&w=600&auto=format&fit=crop',
    likes: 277,
    comments: []
  },
  {
    id: 'reel_onion',
    titleEn: 'Local Red Onions (Piaaj)',
    titleBn: 'দেশি লাল পেঁয়াজ (ভালো করে শুকানো)',
    sellerEn: 'Pabna Onion Syndicate',
    sellerBn: 'পাবনা পেঁয়াজ সমবায় সমিতি',
    sellerRating: 4.75,
    sellerJobs: 512,
    locationEn: 'Santhia, Pabna',
    locationBn: 'সাথিয়া, পাবনা',
    distanceKm: 165,
    stockEn: '8.5 Tons Available',
    stockBn: '৮.৫ টন মজুদ আছে',
    pricePerUnitEn: '65 BDT',
    pricePerUnitBn: '৬৫ টাকা',
    unitEn: 'KG',
    unitBn: 'কেজি',
    category: 'onion',
    zoneEn: 'Buffer',
    zoneBn: 'বাফার',
    zoneDescEn: 'Dry, matured red onions with high shelf-life. Premium sorting done under DAE instruction.',
    zoneDescBn: 'নিখুঁতভাবে শুকানো টেকসই ভালো মানের পেঁয়াজ। পাবনা এগ্রো জোনের সেরা ফসল।',
    bgGradient: 'from-amber-950/90 to-rose-950/20',
    imageUrl: 'https://images.unsplash.com/photo-1508747703725-719ae257c84a?q=80&w=600&auto=format&fit=crop',
    likes: 319,
    comments: []
  },
  {
    id: 'reel_banana',
    titleEn: 'Sabori Banana Commercial Lots',
    titleBn: 'সবরি কলা (বাণিজ্যিক পাইকারি কাদি)',
    sellerEn: 'Narsingdi Fruit Garden',
    sellerBn: 'নরসিংদী কলা বাগান লট',
    sellerRating: 4.82,
    sellerJobs: 98,
    locationEn: 'Sadar, Narsingdi',
    locationBn: 'সদর, নরসিংদী',
    distanceKm: 60,
    stockEn: '1,200 Bunches Available',
    stockBn: '১,২০০ কাদি উপলব্ধ',
    pricePerUnitEn: '180 BDT',
    pricePerUnitBn: '১৮০ টাকা',
    unitEn: 'Bunch',
    unitBn: 'কাদি',
    category: 'banana',
    zoneEn: 'Flash',
    zoneBn: 'ফ্ল্যাশ',
    zoneDescEn: 'Naturally ripened, secure support packaging preventing any bruising in transit.',
    zoneDescBn: 'সম্পূর্ণ প্রাকৃতিকভাবে পাকানো মিষ্টি সবরি কলা। ধাক্কামুক্ত পরিবহনের বিশেষ ব্যবস্থা।',
    bgGradient: 'from-yellow-950/80 to-stone-900/35',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=600&auto=format&fit=crop',
    likes: 412,
    comments: []
  },
  {
    id: 'reel_rice',
    titleEn: 'Premium Miniket Rice (Auto-milled)',
    titleBn: 'প্রিমিয়াম মিনিকেট চাল (সাদা উজ্জ্বল)',
    sellerEn: 'Dinajpur Auto Rice Mill',
    sellerBn: 'দিনাজপুর অটো রাইস মিলস',
    sellerRating: 4.96,
    sellerJobs: 654,
    locationEn: 'Sadar, Dinajpur',
    locationBn: 'সদর, দিনাজপুর',
    distanceKm: 310,
    stockEn: '500 Bags (25 Tons)',
    stockBn: '৫০০ বস্তা (২৫ টন)',
    pricePerUnitEn: '3,400 BDT',
    pricePerUnitBn: '৩,৪০০ টাকা',
    unitEn: 'Bag (50 KG)',
    unitBn: 'বস্তা (৫০ কেজি)',
    category: 'rice',
    zoneEn: 'Vault',
    zoneBn: 'ভল্ট',
    zoneDescEn: 'Super glossy 100% sorted rice. Double polished. Moisture percentage maintained below 12%.',
    zoneDescBn: '১০০% সুষম ও ঝকঝকে অটো-রাইস চাল। আর্দ্রতা সঠিকভাবে ১২% এর নিচে ধরে রাখা হয়েছে।',
    bgGradient: 'from-neutral-900 to-amber-950/10',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=600&auto=format&fit=crop',
    likes: 832,
    comments: []
  },
  {
    id: 'reel_dates',
    titleEn: 'Premium Safawi Arabic Dates',
    titleBn: 'প্রিমিয়াম সাফাভি সৌদি খেজুর',
    sellerEn: 'Moghbazar Importers Ltd.',
    sellerBn: 'মগবাজার ইম্পোর্টার্স লিঃ',
    sellerRating: 4.86,
    sellerJobs: 110,
    locationEn: 'Tejgaon Cold Storage, Dhaka',
    locationBn: 'তেজগাঁও কোল্ড স্টোরেজ, ঢাকা',
    distanceKm: 18,
    stockEn: '150 Cartons Available',
    stockBn: '১৫০ কার্টন উপলব্ধ',
    pricePerUnitEn: '4,500 BDT',
    pricePerUnitBn: '৪,৫০০ টাকা',
    unitEn: 'Carton (10 KG)',
    unitBn: 'কার্টন (১০ কেজি)',
    category: 'dates',
    zoneEn: 'Vault',
    zoneBn: 'ভল্ট',
    zoneDescEn: 'Air-locked imported soft nutritious dates. Cold-vault humidity monitored daily.',
    zoneDescBn: 'আমদানিকৃত নরম মিষ্টি সাফাভি খেজুর। ময়েশ্চার ও তাপমাত্রা সুরক্ষায় কোল্ড-ভল্ট নিয়ন্ত্রিত।',
    bgGradient: 'from-stone-950 to-amber-950/60',
    imageUrl: 'https://images.unsplash.com/photo-1569470451072-68314f596acc?q=80&w=600&auto=format&fit=crop',
    likes: 672,
    comments: []
  }
];

export const MOCK_SAAO: SAAOInfo = {
  nameEn: 'Md. Mahmudul Hasan',
  nameBn: 'মোঃ মাহমুদুল হাসান',
  designationEn: 'Sub-Assistant Agriculture Officer (SAAO)',
  designationBn: 'উপ-সহকারী কৃষি কর্মকর্তা (এসএএও)',
  contact: '+8801712345678',
  upazilaEn: 'Shibganj',
  upazilaBn: 'শিবগঞ্জ',
  districtEn: 'Bogura',
  districtBn: 'বগুড়া',
  avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=300&auto=format&fit=crop',
  availabilityEn: 'Active Now (09:00 AM - 05:00 PM)',
  availabilityBn: 'সক্রিয় আছেন (সকাল ০৯:০০ - বিকাল ০৫:০০)'
};

export const TRANSLATIONS = {
  en: {
    appTitle: 'AgroTrust',
    tagline: 'Trust-backed Agro-Fintech Platform',
    motto: 'Securing Bangladesh Agriculture with FinTech & DAE Integrations',
    
    // Auth & Onboarding
    phoneLabel: 'Enter Mobile Number',
    phonePlaceholder: '17XXXXXXXX',
    sendOtp: 'Send OTP SMS',
    sendingOtp: 'Sending Secure OTP...',
    otpLabel: 'Enter 4-Digit Security OTP PIN',
    verifyOtp: 'Verify Token',
    nidLabel: 'Smart National ID (NID) Card Number',
    nidPlaceholder: 'XXXXXXXXXX (10 or 17 Digits)',
    dobLabel: 'Date of Birth (DD-MM-YYYY)',
    dobPlaceholder: '01-01-1994',
    verifyProfile: 'Query National Porichoy Govt API',
    verifying: 'Connecting Gateway: Security Handshake...',
    onboardingSub: 'Secure Biometric & NID Smart-Escrow Ledger verification',
    profileVerified: 'Porichoy API: Citizen NID Verified!',
    welcomeBack: 'Welcome, Citizen!',

    // Portals
    buyerPortal: 'Buyer Portal',
    sellerPortal: 'Farmer Portal',
    buyerTerminal: 'Escrow Feed',
    sellerTerminal: 'Dispatch Center',
    
    // Categories
    cat_all: 'All',
    cat_vegetables: 'Vegetables',
    cat_fruits: 'Fruits',
    cat_dry_fruits: 'Dry Fruits',
    cat_grains: 'Grains & Pulses',
    cat_chickens: 'Chickens',
    cat_ducks: 'Ducks',
    cat_beef: 'Beef Meat',
    cat_cows: 'Cows',
    cat_goats: 'Goats',

    // Feed Overlay
    instantBuy: 'Liquidate & Buy',
    distance: 'Distance',
    stockPrefix: 'Stock:',
    verifiedSeller: 'Verified Seller',
    trustScore: 'Trust Score',
    transacted: 'Escrows Closed',
    currencySym: '৳',
    currencyName: 'BDT',

    // Seller Dispatch Form
    cropDetailHeader: 'Publish Agro-Dispatch Verification',
    cropTitleLabel: 'Crop Name / Title',
    cropPlaceholder: 'e.g., Katari Naazir Paddy, Shibganj',
    unitLabel: 'Distribution Unit Scale',
    priceLabel: 'Asking Price per Unit (BDT)',
    zoneSelectLabel: 'Logistics Velocity Zone',
    zone_flash: 'Flash Zone (Perishables under 24 hrs)',
    zone_buffer: 'Buffer Zone (DAE Standard Cold Chain)',
    zone_vault: 'Vault Zone (High-Security Warehouse Collateral)',
    uploadProof: 'Launch Freshness Quality Scanner Camera',
    recordingActive: 'Camera feed initiated... Snap high-res token!',
    publishBtn: 'Register Dispatch & Stream',
    dispatchSuccess: 'Dispatch successfully streamed! Live on Agro-Reels',

    // DAE Officer Block
    daeHeader: 'DAE Regional Support Integrations',
    daeSub: 'Linked via geo-location boundary to Shibganj, Bogura DAE Sector',
    callOfficer: 'Call SAAO Officer',
    msgOfficer: 'SMS Proof Matrix',
    officerStatus: 'Duty Status',

    // Settings
    settingsHeader: 'System Terminal Configurator',
    identityHeader: 'Porichoy Verified NID Registry',
    citizenName: 'Full Registered Name',
    nidCard: 'Registered Smart NID',
    systemConfig: 'Regional Localization Config',
    themeLabel: 'Application Interface Theme',
    langLabel: 'Core Language System',
    financialClearing: 'Financial Clearing Routes (Penny-Drop Verified)',
    bankNo: 'Linked Checking Account',
    routingNo: 'Routing Number',
    mfsWalletSec: 'Linked Mobile MFS Accounts',
    mfsBdt: 'Available Liquid Float',
    locationTelemetry: 'GPS Telemetry Engine Status',
    calibratingTimer: 'Active GPS Satellites Pinged...',
    recalibrateBtn: 'Re-calibrate Coordinates',
    calibrationSuccess: 'Self-corrected accuracy to ± 1.2 meters!',
    
    // Checkout half sheet
    checkoutHeader: 'AgroTrust Escrow Holding Gateway',
    selectWallet: 'Select Secure Cashless Gateway Provider',
    bkashLabel: 'bKash Wallet Hold',
    nagadLabel: 'Nagad Wallet Hold',
    bankLabel: 'E-Bank Auto-Clearing Check',
    bdtToHold: 'Hold BDT Collateral Sum',
    enterWalletPhone: 'MFS Registered Mobile ID',
    enterPin: 'Gateway Security PIN Code',
    securePayment: 'Acquire Secure Holding Escrow',
    escrowProcessing: 'Initializing smart-contract holding ledger...',
    escrowHeld: 'ESCROW COLLATERAL DEPOSITED',
    trxSuccess: 'Holding Ledger Initialized: Ledger state locked as HELD.',
    mapTrackingHeader: 'Real-time DAE Secured Shipping Route Tracker',
    deliveryVehicle: 'Consignment vehicle registration: Dhaka Metro-SH-112',
    transitProgress: 'Distance remaining: 1.2 KM. Arriving in Shibganj soon.',
    closeDrawer: 'Minimize Escrow Tracker',

    // Comment Section
    commentsTitle: 'Consignment Comments',
    addCommentPlace: 'Ask seller about moisture, sorting, or cold chain...',
    postBtn: 'Post',
  },
  bn: {
    appTitle: 'এগ্রোট্রাস্ট',
    tagline: 'নিরাপদ কৃষি ও কৃষি-ফিনটেক প্ল্যাটফর্ম',
    motto: 'ডিএই ইন্টিগ্রেশন এবং ফিনটেক সুরক্ষায় বাংলাদেশের কৃষি',
    
    // Auth & Onboarding
    phoneLabel: 'মোবাইল নম্বর লিখুন',
    phonePlaceholder: '১৭XXXXXXXX',
    sendOtp: 'নিরাপদ ওটিপি পাঠান',
    sendingOtp: 'ওটিপি টোকেন পাঠানো হচ্ছে...',
    otpLabel: '৪-ডিজিট ওটিপি পিন লিখুন',
    verifyOtp: 'টোকেন যাচাই করুন',
    nidLabel: 'স্মার্ট জাতীয় পরিচয়পত্র (NID) নম্বর',
    nidPlaceholder: 'XXXXXXXXXX (১০ বা ১৭ ডিজিট)',
    dobLabel: 'জন্ম তারিখ (দিন-মাস-বছর)',
    dobPlaceholder: '০১-০১-১৯৯৪',
    verifyProfile: 'জাতীয় পরিচয়পত্র যাচাই করুন (পরিচয় এপিআই)',
    verifying: 'সার্ভার সংযোগ স্থাপন করা হচ্ছে...',
    onboardingSub: 'নিরাপদ গেটওয়ে এবং স্মার্ট এসক্রো ভেরিফিকেশন',
    profileVerified: 'পরিচয় এপিআই: পরিচয়পত্র সফলভাবে যাচাই হয়েছে!',
    welcomeBack: 'স্বাগতম, বাংলাদেশের গর্বিত নাগরিক!',

    // Portals
    buyerPortal: 'ক্রেতা পোর্টাল',
    sellerPortal: 'কৃষক পোর্টাল',
    buyerTerminal: 'এসক্রো ফিড',
    sellerTerminal: 'ডিসপ্যাচ সেন্টার',
    
    // Categories
    cat_all: 'সব',
    cat_vegetables: 'শাকসবজি',
    cat_fruits: 'ফলমূল',
    cat_dry_fruits: 'শুকনা ফল',
    cat_grains: 'শস্য ও ডাল',
    cat_chickens: 'মুরগি (সোনালী/ব্রয়লার)',
    cat_ducks: 'হাঁস',
    cat_beef: 'গরুর মাংস',
    cat_cows: 'গরু',
    cat_goats: 'ছাগল',

    // Feed Overlay
    instantBuy: 'অবিলম্বে কিনুন',
    distance: 'দূরত্ব',
    stockPrefix: 'মজুদ:',
    verifiedSeller: 'যাচাইকৃত বিক্রেতা',
    trustScore: 'আস্থার হার',
    transacted: 'লেনদেন সংখ্যা',
    currencySym: '৳',
    currencyName: 'টাকা',

    // Seller Dispatch Form
    cropDetailHeader: 'নতুন কৃষি চালান ডিসপ্যাচ ও ভেরিফিকেশন',
    cropTitleLabel: 'ফসলের নাম ও বিবরণ',
    cropPlaceholder: 'যেমন: কাটারিভোগ সুগন্ধি চাল, শিবগঞ্জ',
    unitLabel: 'বিক্রয় ইউনিট পরিমাপ',
    priceLabel: 'প্রতি ইউনিটের দর (টাকা)',
    zoneSelectLabel: 'পরিবহন গতিশীলতা অঞ্চল (ভেলোসিটি জোন)',
    zone_flash: 'ফ্ল্যাশ জোন (২৪ ঘণ্টার মধ্যে কাঁচামাল ডেলিভারি)',
    zone_buffer: 'বাফার জোন (নিরাপদ কোল্ড চেইন সংরক্ষণ)',
    zone_vault: 'ভল্ট জোন (উচ্চ নিরাপত্তা গুদাম সংরক্ষণ)',
    uploadProof: 'তাজা প্রমান যাচাইকারী ক্যামেরা চালু করুন',
    recordingActive: 'ক্যামেরা চালু হয়েছে... তাজা ফসলের ছবি তুলুন!',
    publishBtn: 'ডিসপ্যাচ ও স্ট্রিম লাইভ করুন',
    dispatchSuccess: 'চালান সফলভাবে স্ট্রিমিং হচ্ছে! এগ্রো-রিলস এ লাইভ',

    // DAE Officer Block
    daeHeader: 'ডিএই আঞ্চলিক কৃষি সম্প্রসারণ সহায়তা',
    daeSub: 'শিবগঞ্জ, বগুড়া ডিএই অঞ্চল থেকে জিপিএস সংযোগ স্থাপন করা হয়েছে',
    callOfficer: 'কর্মকর্তাকে কল করুন',
    msgOfficer: 'প্রমাণ পাঠানোর ম্যাট্রিক্স',
    officerStatus: 'ডিউটি স্ট্যাটাস',

    // Settings
    settingsHeader: 'সিস্টেম কনফিগারেশন টার্মিনাল',
    identityHeader: 'পরিচয় এপিআই সম্পর্কিত এনআইডি তথ্য',
    citizenName: 'নিবন্ধিত নাগরিকের নাম',
    nidCard: 'স্মার্ট এনআইডি কার্ড',
    systemConfig: 'আঞ্চলিক লোকাল সেটআপ',
    themeLabel: 'অ্যাপ্লিকেশন ইন্টারফেস থিম',
    langLabel: 'স্মার্ট ভাষা নির্ধারণ',
    financialClearing: 'আর্থিক লেনদেন পদ্ধতি (পেনি-ড্রপ যাচাইকৃত)',
    bankNo: 'সংযুক্ত ব্যাংক হিসাব নম্বর',
    routingNo: 'রাউটিং নাম্বার',
    mfsWalletSec: 'সংযুক্ত এমএফএস ওয়ালেট বুক',
    mfsBdt: 'উপলব্ধ ক্যাশ ব্যালেন্স',
    locationTelemetry: 'জিপিএস স্যাটেলাইট সিগন্যাল স্থিতি',
    calibratingTimer: 'জিপিএস সংযোগ পুনর্গঠন করা হচ্ছে...',
    recalibrateBtn: 'স্থানাঙ্ক পুনর্নির্ধারণ করুন',
    calibrationSuccess: 'নির্ভুলতার মাত্রা ± ১.২ মিটারে সঠিক করা হয়েছে!',
    
    // Checkout half sheet
    checkoutHeader: 'এগ্রোট্রাস্ট এসক্রো হোল্ডিং গেটওয়ে',
    selectWallet: 'নিরাপদ ডিজিটাল ক্যাশলেস গেটওয়ে নির্বাচন করুন',
    bkashLabel: 'বিকাশ ওয়ালেট হোল্ড',
    nagadLabel: 'নগদ ওয়ালেট হোল্ড',
    bankLabel: 'ব্যাংক হিসাব ক্লিয়ারিং ট্রান্সফার',
    bdtToHold: 'হোল্ডকৃত সুরক্ষামূল্য (এগ্রো এসক্রো)',
    enterWalletPhone: 'এমএফএস রেজিস্টার্ড মোবাইল নম্বর',
    enterPin: 'গেটওয়ে সিকিউরিটি পিন নম্বর',
    securePayment: 'এসক্রো চুক্তিপত্র লক করুন',
    escrowProcessing: 'ডিজিটাল স্মার্ট এসক্রো চুক্তি তৈরি হচ্ছে...',
    escrowHeld: 'এসক্রো পেমেন্ট সফলভাবে সংরক্ষিত (HELD)',
    trxSuccess: 'এসক্রো পেমেন্ট সম্পন্ন: চুক্তিমূল্য এগ্রোট্রাস্ট তত্ত্বাবধানে সুরক্ষিত।',
    mapTrackingHeader: 'রিয়েল-টাইম ডিএই হাই-সিকিউরিটি শিপিং ট্র্যাকার',
    deliveryVehicle: 'নিবন্ধিত পণ্যবাহী গাড়ি: ঢাকা মেট্রো-শ-১১২',
    transitProgress: 'গন্তব্যের দূরত্ব: ১.২ কি.মি.। কিছুক্ষণের মধ্যে শিবগঞ্জ পৌঁছাবে।',
    closeDrawer: 'এসক্রো ট্র্যাকার বন্ধ করুন',

    // Comment Section
    commentsTitle: 'চালান সম্পর্কিত আলোচনা',
    addCommentPlace: 'আর্দ্রতা, গ্রেডিং বা কোল্ড চেইন সম্পর্কে প্রশ্ন করুন...',
    postBtn: 'মন্তব্য করুন',
  }
};

export function formatCurrency(amount: number, lang: 'en' | 'bn'): string {
  if (lang === 'bn') {
    // English number translation helper to Bengali digits
    const englishNumbers = ['0','1','2','3','4','5','6','7','8','9'];
    const bengaliNumbers = ['০','১','২','৩','৪','৫','৬','৭','৮','৯'];
    const formatted = amount.toLocaleString('bn-BD');
    return formatted.replace(/[0-9]/g, (w) => bengaliNumbers[englishNumbers.indexOf(w)]) + ' টাকা';
  } else {
    return '৳ ' + amount.toLocaleString('en-US');
  }
}

export function convertNumber(numStr: string | number, lang: 'en' | 'bn'): string {
  const str = String(numStr);
  if (lang === 'bn') {
    const englishNumbers = ['0','1','2','3','4','5','6','7','8','9'];
    const bengaliNumbers = ['০','১','২','৩','৪','৫','৬','৭','৮','৯'];
    return str.replace(/[0-9]/g, (w) => bengaliNumbers[englishNumbers.indexOf(w)]);
  }
  return str;
}

export const CATEGORIES_STRUCTURE = [
  {
    id: 'vegetables',
    nameEn: 'Vegetables',
    nameBn: 'শাকসবজি',
    icon: 'Layers',
    subcategories: [
      { id: 'spinach', nameEn: 'Spinach', nameBn: 'পালং শাক' },
      { id: 'cabbage', nameEn: 'Cabbage', nameBn: 'বাঁধাকপি' },
      { id: 'green_chilli', nameEn: 'Green Chilli', nameBn: 'কাঁচা মরিচ' },
      { id: 'onion', nameEn: 'Onion', nameBn: 'পেঁয়াজ' },
      { id: 'ginger', nameEn: 'Ginger', nameBn: 'আদা' },
      { id: 'potato', nameEn: 'Potato', nameBn: 'আলু' },
      { id: 'tomato', nameEn: 'Tomato', nameBn: 'টমেটো' }
    ]
  },
  {
    id: 'fruits',
    nameEn: 'Fruits',
    nameBn: 'ফলমূল',
    icon: 'PlusCircle',
    subcategories: [
      { id: 'mango', nameEn: 'Mango', nameBn: 'আম' },
      { id: 'pineapple', nameEn: 'Pineapple', nameBn: 'আনারস' },
      { id: 'banana', nameEn: 'Banana', nameBn: 'কলা' },
      { id: 'jackfruit', nameEn: 'Jackfruit', nameBn: 'কাঁঠাল' },
      { id: 'papaya', nameEn: 'Papaya', nameBn: 'পেঁপে' }
    ]
  },
  {
    id: 'dry_fruits',
    nameEn: 'Dry Fruits',
    nameBn: 'শুকনা ফল',
    icon: 'Shield',
    subcategories: [
      { id: 'dates', nameEn: 'Dates', nameBn: 'খেজুর' },
      { id: 'almonds', nameEn: 'Almonds', nameBn: 'কাঠবাদাম' },
      { id: 'raisins', nameEn: 'Raisins', nameBn: 'কিসমিস' },
      { id: 'cashews', nameEn: 'Cashews', nameBn: 'কাজুবাদাম' }
    ]
  },
  {
    id: 'grains',
    nameEn: 'Grains & Pulses',
    nameBn: 'শস্য ও ডাল',
    icon: 'Coins',
    subcategories: [
      { id: 'rice', nameEn: 'Rice', nameBn: 'চাল' },
      { id: 'wheat', nameEn: 'Wheat', nameBn: 'গম' },
      { id: 'lentils', nameEn: 'Lentils', nameBn: 'মসুর ডাল' },
      { id: 'chickpeas', nameEn: 'Chickpeas', nameBn: 'ছোলা' }
    ]
  },
  {
    id: 'chickens',
    nameEn: 'Chickens',
    nameBn: 'মুরগি',
    icon: 'Activity',
    subcategories: [
      { id: 'shonali', nameEn: 'Shonali Chicken', nameBn: 'সোনালী মুরগি' },
      { id: 'broiler', nameEn: 'Broiler Chicken', nameBn: 'ব্রয়লার মুরগি' }
    ]
  },
  {
    id: 'ducks',
    nameEn: 'Ducks',
    nameBn: 'হাঁস',
    icon: 'Globe',
    subcategories: [
      { id: 'ducks', nameEn: 'Ducks (All)', nameBn: 'হাঁস (সব জাত)' }
    ]
  },
  {
    id: 'beef',
    nameEn: 'Beef Meat',
    nameBn: 'গরুর মাংস',
    icon: 'TrendingUp',
    subcategories: [
      { id: 'beef', nameEn: 'Beef Meat', nameBn: 'গরুর মাংস' }
    ]
  },
  {
    id: 'cows',
    nameEn: 'Cows',
    nameBn: 'গরু',
    icon: 'CheckCircle',
    subcategories: [
      { id: 'cows', nameEn: 'Cows (Live)', nameBn: 'জীবন্ত গরু' }
    ]
  },
  {
    id: 'goats',
    nameEn: 'Goats',
    nameBn: 'ছাগল',
    icon: 'Smartphone',
    subcategories: [
      { id: 'goats', nameEn: 'Goats (Live)', nameBn: 'জীবন্ত ছাগল' }
    ]
  }
];
